version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/YusukeIwaki/appetize-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            go get github.com/mitchellh/go-homedir
            go get github.com/pkg/errors
            go get github.com/spf13/cobra
            go get github.com/spf13/viper
      - run:
          name: Test optional package
          command: |
            go test optional/*
      - run:
          name: Build for darwin/amd64
          command: |
            mkdir -p out/binary/darwin
            GOOS=darwin GOARCH=amd64 go build -o out/binary/darwin/appetize main.go
      - run:
          name: Build for linux/amd64
          command: |
            mkdir -p out/binary/amd64
            GOOS=linux GOARCH=amd64 go build -o out/binary/amd64/appetize main.go
      - store_artifacts:
          path: out/binary
          destination: binary